# -*- coding: utf-8 -*-
"""basic_vpc_launch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nu1N8nJFO_Uo5BTYuBMxKB5Buwaet5mK

This is based on an online example of how to create a VPC in Python. 
For it to work, you need the following files:

aws_accounts.json, aws_ec2.json, aws_local.py, key0123.pem, setup_script.txt

aws_accounts.json and key0123.pem are files with credentials in them, but the rest can be found at https://www.github.com/autindesosa/aws_tools
"""

import os
from aws_local import *

s3 = service('s3','s3iam',quick_iam_dxry())
ec2 = service('ec2','ec2iam',quick_iam_dxry())

vpc = ec2.create_vpc(CidrBlock = '172.16.0.0/16') #create a VPC
vpc.create_tags(Tags = [{'Key':'Name','Value':'my_vpc'}])
vpc.wait_until_available()

ec2client = ec2.meta.client

internetgateway = ec2.create_internet_gateway()

vpc.attach_internet_gateway(InternetGatewayId = internetgateway.id)

routetable = vpc.create_route_table()

route = routetable.create_route(DestinationCidrBlock = '0.0.0.0/0',
                                GatewayId = internetgateway.id)

subnet = ec2.create_subnet(CidrBlock = '172.16.1.0/24',
                           VpcId = vpc.id)

routetable.associate_with_subnet(SubnetId = subnet.id)

securitygroup = ec2.create_security_group(GroupName = 'SSH-ONLY',
                                          Description = 'Only allow SSH traffic',
                                          VpcId = vpc.id)

securitygroup.authorize_ingress(CidrIp = '0.0.0.0/0',
                                IpProtocol = 'tcp',
                                FromPort=22,
                                ToPort=22)

ni_dxry = {'SubnetId':subnet.id,
           'DeviceIndex':0,
           'AssociatePublicIpAddress':True,
           'Groups':[securitygroup.group_id],
           }

SCRIPT = open('setup_script.txt').read()
SCRIPT

ec2_d = json.load(open('aws_ec2.json'))
ec2_d

instances = ec2.create_instances(ImageId = ec2_d['ImageId'],
                    InstanceType = ec2_d['InstanceType'],
                    MaxCount=1,
                    MinCount=1,
                    NetworkInterfaces = [ni_dxry],
                    UserData = SCRIPT,
                    KeyName = 'key0123')

